### ISSUE TITLE
Obviously stolen code lol

### ISSUE THREAD

**Issue by J0k3r-Squ4d** [ProgrammerGaurav/DDos-Attack#5]
`Proof this is stolen code:`

1, in the description he says to do `python run.py`

2, in the files list you'll notice that the file is `xerxes.c` which is famously crafted by Zanjarjamal, not this code thief

**Comment by ProgrammerGaurav** [comment]
are you a 13-year-old Kiddo??
It is an Open source tool so I took it and modified it and automated it so that even beginners can use it.
You can report this to GitHub and so that they can ignore you....and you can also take my code and improve it.....or you lack skills??? XD LOL

**Comment by J0k3r-Squ4d** [comment]
Except you didn't make it better lmfaoo. You literally stole the xerxes code and only added an easy ass `run.py` script lol. Keep acting like you done elite h4x0r lol. You ain't shit skid

**Comment by sahal-mulki** [comment]
This is heated

**Comment by ProgrammerGaurav** [comment]
You can report it to Github or the actual owner, who are you to say me this?
